#VESTA_INI_VER 3.1.8  3.4.5

/home/kirill/Skoltech/soft/VESTA/PowderPlot/PowderPlot.jar
/home/kirill/Skoltech/soft/VESTA/template.ins
100
10 10 2
 1.600 1
8 9 0
66 32 860 765
314 150
12 0 0
45 2 30 10 45 10
DejaVu Sans Mono
9
607 202 772 708
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  0   0  -1  -1
  1   4  11   1   7  -1   8  -1   9  -1   0
20 2 // Recent files
/home/kirill/Skoltech/tutorials/vasp_tutorials/bulk-part2/e05_cd-Si-relaxation/CONTCAR
/home/kirill/Skoltech/tutorials/vasp_tutorials/bulk-part2/e05_cd-Si-relaxation/POSCAR
